org: tripleleads
app: leads-backend
service: leads-backend
frameworkVersion: '3'

provider:
  name: aws
  region: ca-central-1
  runtime: python3.9

functions:
  test:
    handler: handler.test
    events:
      - http:
          path: test
          method: post
  joinWaitlist:
    handler: handlers/user/waitlist.joinWaitlist
    events:
      - httpApi:
          path: /joinWaitlist
          method: post